/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:624787:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider1:624787:

public void directoryList_click(GDropList source, GEvent event) { //_CODE_:dLDirectory:935160:
  println("dLDirectory - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dLDirectory:935160:

public void dropList2_click1(GDropList source, GEvent event) { //_CODE_:dropList2:687392:
  println("dropList2 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList2:687392:

public void selectScan_click(GButton source, GEvent event) { //_CODE_:btnSelectScan:945866:
  println("btnSelectScan - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnSelectScan:945866:

public void batchUpload_clicked(GCheckbox source, GEvent event) { //_CODE_:chbxBatchUpload:595794:
  println("chbxBatchUpload - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:chbxBatchUpload:595794:

public void txtLog_change(GTextArea source, GEvent event) { //_CODE_:txtLog:548988:
  println("txtLog - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txtLog:548988:

public void btnFolder_click(GButton source, GEvent event) { //_CODE_:btnFolder:261356:
  println("btnFolder - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnFolder:261356:

public void btnUpload_click(GButton source, GEvent event) { //_CODE_:btnUpload:463455:
  println("btnUpload - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnUpload:463455:

public void txfdScan_change(GTextField source, GEvent event) { //_CODE_:txfdScan:581755:
  println("txfdScan - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txfdScan:581755:

public void txfdFolder_change(GTextField source, GEvent event) { //_CODE_:txfdFolder:987414:
  println("txfdFolder - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txfdFolder:987414:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Manuscript Uploader");
  lblFileUpload = new GLabel(this, 10, 10, 80, 20);
  lblFileUpload.setText("File upload");
  lblFileUpload.setOpaque(false);
  lblProgress = new GLabel(this, 10, 220, 80, 20);
  lblProgress.setText("Progress:");
  lblProgress.setOpaque(false);
  slider1 = new GSlider(this, 100, 220, 373, 24, 10.0);
  slider1.setLimits(0.5, 0.0, 1.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  dLDirectory = new GDropList(this, 10, 90, 461, 114, 5);
  dLDirectory.setItems(loadStrings("list_935160"), 0);
  dLDirectory.addEventHandler(this, "directoryList_click");
  lblFolder = new GLabel(this, 10, 70, 80, 20);
  lblFolder.setText("Folder");
  lblFolder.setOpaque(false);
  lblSubfolder = new GLabel(this, 10, 120, 80, 20);
  lblSubfolder.setText("Subfolder");
  lblSubfolder.setOpaque(false);
  dropList2 = new GDropList(this, 10, 140, 460, 80, 3);
  dropList2.setItems(loadStrings("list_687392"), 0);
  dropList2.addEventHandler(this, "dropList2_click1");
  btnSelectScan = new GButton(this, 110, 10, 53, 23);
  btnSelectScan.setText("select");
  btnSelectScan.addEventHandler(this, "selectScan_click");
  chbxBatchUpload = new GCheckbox(this, 10, 40, 120, 20);
  chbxBatchUpload.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  chbxBatchUpload.setText("Batch upload");
  chbxBatchUpload.setOpaque(false);
  chbxBatchUpload.addEventHandler(this, "batchUpload_clicked");
  txtLog = new GTextArea(this, 10, 270, 461, 190, G4P.SCROLLBARS_VERTICAL_ONLY);
  txtLog.setOpaque(true);
  txtLog.addEventHandler(this, "txtLog_change");
  btnFolder = new GButton(this, 110, 40, 54, 22);
  btnFolder.setText("select");
  btnFolder.addEventHandler(this, "btnFolder_click");
  btnUpload = new GButton(this, 350, 170, 120, 40);
  btnUpload.setText("Upload");
  btnUpload.addEventHandler(this, "btnUpload_click");
  txfdScan = new GTextField(this, 170, 10, 300, 20, G4P.SCROLLBARS_NONE);
  txfdScan.setPromptText("scan folder");
  txfdScan.setOpaque(true);
  txfdScan.addEventHandler(this, "txfdScan_change");
  txfdFolder = new GTextField(this, 170, 40, 300, 20, G4P.SCROLLBARS_NONE);
  txfdFolder.setPromptText("folder with several scans");
  txfdFolder.setOpaque(true);
  txfdFolder.addEventHandler(this, "txfdFolder_change");
  lblProcessLog = new GLabel(this, 10, 250, 80, 20);
  lblProcessLog.setText("Process log:");
  lblProcessLog.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel lblFileUpload; 
GLabel lblProgress; 
GSlider slider1; 
GDropList dLDirectory; 
GLabel lblFolder; 
GLabel lblSubfolder; 
GDropList dropList2; 
GButton btnSelectScan; 
GCheckbox chbxBatchUpload; 
GTextArea txtLog; 
GButton btnFolder; 
GButton btnUpload; 
GTextField txfdScan; 
GTextField txfdFolder; 
GLabel lblProcessLog; 
