import java.awt.Font;

import g4p_controls.G4P;
import g4p_controls.GAlign;
import g4p_controls.GButton;
import g4p_controls.GCScheme;
import g4p_controls.GGroup;
import g4p_controls.GImageButton;
import g4p_controls.GImageToggleButton;
import g4p_controls.GLabel;
import g4p_controls.GPanel;
import g4p_controls.GTextArea;
import g4p_controls.GTextField;
import g4p_controls.GWindow;
import processing.core.PApplet;

public class GUI {
	public GButton first_page_button;
	public GButton last_page_button;
	public GTextField name_text;
	public GLabel project_info;
	public GLabel name;
	public GLabel code_label;
	public GTextField code_text;
	public GLabel author_label;
	public GLabel project_comments_label;
	public GLabel page_info_label;
	public GLabel page_comments_label;
	public GLabel number_label;
	public GLabel shutter_control_label;
	public GLabel camera_config_label;
	public GLabel camera_A_label;
	public GTextField author_text;
	public GTextField project_comments_text;
	public GLabel camera_B_label;
	public GTextField page_comments_text;
	public GTextField page_num_text;
	public GButton normal_shutter_button;
	public GButton repeat_shutter_button;
	// public GButton subpage_shutter_button;
	public GButton calibration_shutter_button;
	public GButton trigger_button;
	public GButton camera_A_connected_button;
	public GButton camera_A_active_button;
	public GButton camera_A_inactive_button;
	public GButton camera_B_connected_button;
	public GButton camera_B_active_button;
	public GButton camera_B_inactive_button;
	public GButton parameters_button;
	public GButton load_button;
	public GButton edit_button;
	public GButton close_button;
	public GButton new_button;
	public GTextField page_search_text;
	public GLabel page_search_label;
	public GButton liveView_button;

	// Group 2 controls
	GWindow window;
	GLabel lblGroup2Controls;
	GImageToggleButton grp2_a;
	GButton grp2_b;
	GPanel grp2_c;
	GTextArea grp2_textArea;
	GLabel grp2_d;
	GImageButton grp2_e;

	ManuCaptureContext context;
	ManuCapture_v1_1 parent;

	GGroup grpWin;

	public GUI() {
	}

	// Create all the GUI controls.
	// autogenerated do not edit
	public void createGUI(ManuCaptureContext context) {
		this.parent = context.parent;
		this.context = context;
		GUI gui = this;

		grpWin = new GGroup(parent);

		gui.first_page_button = new GButton(parent, 11, 90, 122, 24);
		gui.first_page_button.setText("FIRST PAGE");
		gui.first_page_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.first_page_button.addEventHandler(parent, "first_page_button_click");
		gui.last_page_button = new GButton(parent, 141, 90, 122, 24);
		gui.last_page_button.setText("LAST PAGE");
		gui.last_page_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.last_page_button.addEventHandler(parent, "last_page_button_click");
		gui.page_info_label = new GLabel(parent, 300, 276, 80, 20);
		gui.page_info_label.setText("PAGE INFO");
		gui.page_info_label.setTextBold();
		gui.page_info_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.page_info_label.setOpaque(true);
		gui.page_comments_label = new GLabel(parent, 302, 326, 80, 20);
		gui.page_comments_label.setText("Comments:");
		gui.page_comments_label.setTextBold();
		gui.page_comments_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.page_comments_label.setOpaque(true);
		gui.number_label = new GLabel(parent, 302, 410, 80, 20);
		gui.number_label.setText("Number:");
		gui.number_label.setTextBold();
		gui.number_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.number_label.setOpaque(true);
		gui.shutter_control_label = new GLabel(parent, 300, 450, 200, 24);
		gui.shutter_control_label.setText("SHUTTER CONTROL:");
		gui.shutter_control_label.setTextBold();
		gui.shutter_control_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.shutter_control_label.setOpaque(true);
		gui.camera_config_label = new GLabel(parent, 300, 684, 200, 20);
		gui.camera_config_label.setText("CAMERA CONFIGURATION:");
		gui.camera_config_label.setTextBold();
		gui.camera_config_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_config_label.setOpaque(true);
		gui.camera_A_label = new GLabel(parent, 407, 719, 80, 20);
		gui.camera_A_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
		gui.camera_A_label.setText("CAMERA A");
		gui.camera_A_label.setTextBold();
		gui.camera_A_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_A_label.setOpaque(true);
		gui.camera_B_label = new GLabel(parent, 407, 852, 80, 20);
		gui.camera_B_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
		gui.camera_B_label.setText("CAMERA B");
		gui.camera_B_label.setTextBold();
		gui.camera_B_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_B_label.setOpaque(true);
		gui.page_comments_text = new GTextField(parent, 380, 326, 200, 80, G4P.SCROLLBARS_NONE);
		gui.page_comments_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.page_comments_text.setOpaque(true);
		gui.page_comments_text.addEventHandler(parent, "page_comments_text_change");
		gui.page_num_text = new GTextField(parent, 380, 410, 200, 20, G4P.SCROLLBARS_NONE);
		gui.page_num_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.page_num_text.setOpaque(true);
		gui.page_num_text.addEventHandler(parent, "page_num_text_change");
		gui.normal_shutter_button = new GButton(parent, 386, 488, 122, 24);
		gui.normal_shutter_button.setText("NORMAL");
		gui.normal_shutter_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.normal_shutter_button.addEventHandler(parent, "normal_shutter_click1");
		gui.repeat_shutter_button = new GButton(parent, 386, 517, 122, 24);
		gui.repeat_shutter_button.setText("REPEAT");
		gui.repeat_shutter_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.repeat_shutter_button.addEventHandler(parent, "repeat_shutter_click");
		// gui.subpage_shutter_button = new GButton(parent, 386, 547, 122, 24);
		// gui.subpage_shutter_button.setText("SUBPAGE");
		// gui.subpage_shutter_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		// gui.subpage_shutter_button.addEventHandler(parent,
		// "subpage_shutter_click");
		gui.calibration_shutter_button = new GButton(parent, 386, 577, 122, 24);
		gui.calibration_shutter_button.setText("CALIBRATION");
		gui.calibration_shutter_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.calibration_shutter_button.addEventHandler(parent, "calibration_shutter_click");
		gui.trigger_button = new GButton(parent, 386, 619, 122, 48);
		gui.trigger_button.setText("TRIGGER");
		gui.trigger_button.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
		gui.trigger_button.addEventHandler(parent, "trigger_button_click");
		gui.camera_A_connected_button = new GButton(parent, 386, 746, 122, 24);
		gui.camera_A_connected_button.setText("DISCONNECTED");
		gui.camera_A_connected_button.setLocalColorScheme(GCScheme.RED_SCHEME);
		gui.camera_A_connected_button.addEventHandler(parent, "camera_A_connected_click");
		gui.camera_A_active_button = new GButton(parent, 385, 779, 122, 24);
		gui.camera_A_active_button.setText("ACTIVE");
		gui.camera_A_active_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_A_active_button.addEventHandler(parent, "camera_A_active_button_click");
		gui.camera_A_inactive_button = new GButton(parent, 386, 809, 122, 24);
		gui.camera_A_inactive_button.setText("INACTIVE");
		gui.camera_A_inactive_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_A_inactive_button.addEventHandler(parent, "camera_A_inactive_button_click");
		gui.camera_B_connected_button = new GButton(parent, 386, 879, 122, 24);
		gui.camera_B_connected_button.setText("DISCONNECTED");
		gui.camera_B_connected_button.setLocalColorScheme(GCScheme.RED_SCHEME);
		gui.camera_B_connected_button.addEventHandler(parent, "camera_B_connected_click");
		gui.camera_B_active_button = new GButton(parent, 386, 915, 122, 24);
		gui.camera_B_active_button.setText("ACTIVE");
		gui.camera_B_active_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_B_active_button.addEventHandler(parent, "camera_B_active_click");
		gui.camera_B_inactive_button = new GButton(parent, 386, 945, 122, 24);
		gui.camera_B_inactive_button.setText("INACTIVE");
		gui.camera_B_inactive_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.camera_B_inactive_button.addEventHandler(parent, "camera_B_inactive_click");
		gui.parameters_button = new GButton(parent, 386, 994, 122, 24);
		gui.parameters_button.setText("PARAMETERS");
		gui.parameters_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.parameters_button.addEventHandler(parent, "parameters_click");
		gui.load_button = new GButton(parent, -111, 11, 80, 24);
		gui.load_button.setText("LOAD");
		gui.load_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.load_button.addEventHandler(parent, "load_click");
		gui.edit_button = new GButton(parent, 219, 11, 80, 24);
		gui.edit_button.setText("EDIT");
		gui.edit_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.edit_button.addEventHandler(parent, "edit_click");
		
		gui.close_button = new GButton(parent, 289, 11, 80, 24);
		gui.close_button.setText("CLOSE");
		gui.close_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.close_button.addEventHandler(parent, "close_click");
		
		gui.new_button = new GButton(parent, -199, 11, 122, 24);
		gui.new_button.setText("NEW PROJECT");
		gui.new_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.new_button.addEventHandler(parent, "new_button_click");
		gui.page_search_text = new GTextField(parent, 90, 57, 175, 20, G4P.SCROLLBARS_NONE);
		gui.page_search_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.page_search_text.setOpaque(true);
		gui.page_search_text.addEventHandler(parent, "page_search_text_change");
		gui.page_search_label = new GLabel(parent, 10, 57, 80, 20);
		gui.page_search_label.setText("Page search:");
		gui.page_search_label.setTextBold();
		gui.page_search_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.page_search_label.setOpaque(true);
		gui.liveView_button = new GButton(parent, 490, 11, 80, 24);
		gui.liveView_button.setText("LIVEVIEW");
		gui.liveView_button.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		gui.liveView_button.addEventHandler(parent, "liveView_button_click");

		grpWin.addControls(first_page_button, last_page_button, page_info_label, page_comments_label);
		grpWin.addControls(number_label, shutter_control_label, camera_config_label, camera_A_label, camera_B_label);
		grpWin.addControls(page_comments_text, page_num_text, normal_shutter_button, repeat_shutter_button);
		grpWin.addControls(calibration_shutter_button, trigger_button, camera_A_connected_button,
				camera_A_active_button);
		grpWin.addControls(camera_A_inactive_button, camera_B_connected_button, camera_B_active_button,
				camera_B_inactive_button);
		grpWin.addControls(parameters_button, load_button, edit_button, new_button, page_search_text, page_search_label,
				liveView_button);
		
		grpWin.addControls(close_button);
	}

	// Use this method to add additional statements
	// to customise the GUI controls
	public void customGUI() {

		Font font = new Font("Verdana", Font.BOLD, 10);
		GUI gui = this;

		gui.page_comments_label.setFont(font);
		gui.number_label.setFont(font);
		gui.camera_A_label.setFont(font);
		gui.camera_B_label.setFont(font);
		gui.page_search_label.setFont(font);

		Font sectionFont = new Font("Verdana", Font.BOLD, 12);
		gui.page_info_label.setFont(sectionFont);
		gui.shutter_control_label.setFont(sectionFont);
		gui.camera_config_label.setFont(sectionFont);

		gui.normal_shutter_button.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
		gui.camera_A_active_button.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
		gui.camera_B_active_button.setLocalColorScheme(GCScheme.ORANGE_SCHEME);

	}

	public void createGroup2Controls() {
		window = GWindow.getWindow(parent, "Window created by G4P", 0, 0, 480, 430, PApplet.JAVA2D);
		// window.addDrawHandler(this, "drawWin");
		// window.addOnCloseHandler(parent, "close_popup_project_window");
		// grp2_a = new GImageToggleButton(window, 20, 50);
		// String[] imgs = new String[] { "data/tjoff.jpg", "data/tjover.jpg",
		// "data/tjdown.jpg" };
		// grp2_e = new GImageButton(window, 250, 50, imgs, "data/tjmask.png");
		// grp2_c = new GPanel(window, 70, 50, 174, 80, "Tab bar text");
		// grp2_c.setText("Tab bar text");
		// grp2_textArea = new GTextArea(window, 4, 23, 164, 50,
		// G4P.SCROLLBARS_NONE);
		// grp2_textArea.setPromptText("Why not enter some text?");
		// grp2_c.addControl(grp2_textArea);
		// grp2_d = new GLabel(window, 70, 140, 170, 61);
		// grp2_d.setIcon("ghost2.png", 1, GAlign.RIGHT, GAlign.MIDDLE);
		// grp2_d.setText("Casperov");
		// grp2_d.setTextBold();
		grp2_b = new GButton(window, 20, 300, 90, 30);
		grp2_b.setText("OK!");
		grp2_b.addEventHandler(parent, "close_popup_project");

		name_text = new GTextField(window, 80, 106, 200, 20, G4P.SCROLLBARS_NONE);
		name_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		name_text.setOpaque(true);
		name_text.addEventHandler(parent, "name_text_change");
		name_text.setText(context.project.projectName);
		project_info = new GLabel(window, 00, 56, 132, 24);
		project_info.setText("PROJECT INFO");
		project_info.setTextBold();
		project_info.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		project_info.setOpaque(true);
		name = new GLabel(window, 02, 106, 80, 20);
		name.setText("Name:");
		name.setTextBold();
		name.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		name.setOpaque(true);
		code_label = new GLabel(window, 02, 130, 80, 20);
		code_label.setText("Code:");
		code_label.setTextBold();
		code_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		code_label.setOpaque(true);
		code_text = new GTextField(window, 80, 130, 200, 20, G4P.SCROLLBARS_NONE);
		code_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		code_text.setOpaque(true);
		code_text.setText(context.project.projectCode);
		code_text.addEventHandler(parent, "code_text_change");
		author_label = new GLabel(window, 02, 154, 80, 20);
		author_label.setText("Author:");
		author_label.setTextBold();
		author_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		author_label.setOpaque(true);

		author_text = new GTextField(window, 80, 154, 200, 20, G4P.SCROLLBARS_NONE);
		author_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		author_text.setOpaque(true);
		author_text.setText(context.project.projectAuthor);
		author_text.addEventHandler(parent, "author_text_change");

		project_comments_text = new GTextField(window, 80, 178, 200, 80, G4P.SCROLLBARS_NONE);
		project_comments_text.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		project_comments_text.setOpaque(true);
		project_comments_text.setText(context.project.projectComment);
		project_comments_text.addEventHandler(parent, "project_comments_change");

		project_comments_label = new GLabel(window, 02, 178, 80, 20);
		project_comments_label.setText("Comments:");
		project_comments_label.setTextBold();
		project_comments_label.setLocalColorScheme(GCScheme.CYAN_SCHEME);
		project_comments_label.setOpaque(true);

		lblGroup2Controls = new GLabel(window, 20, 20, 440, 20);
		lblGroup2Controls.setText("GROUP 2 CONTROLS");
		lblGroup2Controls.setTextBold();

		Font font = new Font("Verdana", Font.BOLD, 10);
		name.setFont(font);
		code_label.setFont(font);
		author_label.setFont(font);
		project_comments_label.setFont(font);

		Font sectionFont = new Font("Verdana", Font.BOLD, 12);
		project_info.setFont(sectionFont);
	}

}