/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void sldir_change(GSlider source, GEvent event) { //_CODE_:sldrProgress:624787:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:sldrProgress:624787:

public void dlFolder_click(GDropList source, GEvent event) { //_CODE_:dlFolder:935160:
  selectedFolderIndex = source.getSelectedIndex();
  selectedSubfolderIndex = 0;
  subfolders=getSubfolders(selectedFolderIndex);
  dlSubfolder.setItems(subfolders,selectedSubfolderIndex);
} //_CODE_:dlFolder:935160:

public void dlSubfolder_click(GDropList source, GEvent event) { //_CODE_:dlSubfolder:687392:
  selectedSubfolderIndex = source.getSelectedIndex();
} //_CODE_:dlSubfolder:687392:

public void selectScan_click(GButton source, GEvent event) { //_CODE_:btnSelectScan:945866:
  selectFolder("Select the scan folder:", "scanSelected");

} //_CODE_:btnSelectScan:945866:

public void txtLog_change(GTextArea source, GEvent event) { //_CODE_:txtLog:548988:

} //_CODE_:txtLog:548988:

public void btnUpload_click(GButton source, GEvent event) { //_CODE_:btnUpload:463455:
  doUpload = true;
  
  try {
     String cmd = rawTherapeeCommand;
        Runtime.getRuntime().exec(cmd);
      } catch (Exception e) {
        println("Couldn't launch lefs");
  }
  
} //_CODE_:btnUpload:463455:

public void txfdScan_change(GTextField source, GEvent event) { //_CODE_:txfdScan:581755:

} //_CODE_:txfdScan:581755:

public void txfdFolder_change(GTextField source, GEvent event) { //_CODE_:txfdFolder:987414:

} //_CODE_:txfdFolder:987414:

public void btnStop_click(GImageButton source, GEvent event) { //_CODE_:btnStop:209469:
    txtLog.appendText("Stopped\n");
    OscMessage myMessage = new OscMessage("/stop");
    oscP5.send(myMessage, uploaderLocation);  
    String[] lines = {""};
    saveStrings( sketchPath() +  "/../scripts/stopUpload.txt",lines);
} //_CODE_:btnStop:209469:

public void btnReloadThumbnail_click(GButton source, GEvent event) { //_CODE_:btnReloadThumbnail:997964:
  println("btnReloadThumbnail - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnReloadThumbnail:997964:

public void btnSelectFolder_click1(GButton source, GEvent event) { //_CODE_:btnSelectFolder:583545:
  println("btnSelectFolder - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnSelectFolder:583545:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Manuscript Uploader");
  lblFileUpload = new GLabel(this, 10, 10, 80, 20);
  lblFileUpload.setText("Scan upload");
  lblFileUpload.setOpaque(false);
  lblProgress = new GLabel(this, 10, 220, 80, 20);
  lblProgress.setText("Progress:");
  lblProgress.setOpaque(false);
  sldrProgress = new GSlider(this, 100, 220, 373, 24, 10.0);
  sldrProgress.setLimits(0.0, 0.0, 1.0);
  sldrProgress.setNumberFormat(G4P.DECIMAL, 2);
  sldrProgress.setOpaque(false);
  sldrProgress.addEventHandler(this, "sldir_change");
  dlFolder = new GDropList(this, 10, 90, 461, 209, 10);
  dlFolder.setItems(loadStrings("list_935160"), 0);
  dlFolder.addEventHandler(this, "dlFolder_click");
  lblFolder = new GLabel(this, 10, 70, 80, 20);
  lblFolder.setText("Folder");
  lblFolder.setOpaque(false);
  lblSubfolder = new GLabel(this, 10, 120, 80, 20);
  lblSubfolder.setText("Subfolder");
  lblSubfolder.setOpaque(false);
  dlSubfolder = new GDropList(this, 10, 140, 460, 220, 10);
  dlSubfolder.setItems(loadStrings("list_687392"), 0);
  dlSubfolder.addEventHandler(this, "dlSubfolder_click");
  btnSelectScan = new GButton(this, 110, 10, 53, 23);
  btnSelectScan.setText("select");
  btnSelectScan.addEventHandler(this, "selectScan_click");
  txtLog = new GTextArea(this, 10, 270, 461, 190, G4P.SCROLLBARS_VERTICAL_ONLY);
  txtLog.setOpaque(true);
  txtLog.addEventHandler(this, "txtLog_change");
  btnUpload = new GButton(this, 10, 170, 120, 40);
  btnUpload.setText("Upload");
  btnUpload.addEventHandler(this, "btnUpload_click");
  txfdScan = new GTextField(this, 170, 10, 300, 20, G4P.SCROLLBARS_NONE);
  txfdScan.setPromptText("scan folder");
  txfdScan.setOpaque(true);
  txfdScan.addEventHandler(this, "txfdScan_change");
  txfdFolder = new GTextField(this, 170, 40, 300, 20, G4P.SCROLLBARS_NONE);
  txfdFolder.setPromptText("Target output folder");
  txfdFolder.setOpaque(true);
  txfdFolder.addEventHandler(this, "txfdFolder_change");
  lblProcessLog = new GLabel(this, 10, 250, 80, 20);
  lblProcessLog.setText("Process log:");
  lblProcessLog.setOpaque(false);
    btnStop = new GImageButton(this, 430, 170, 40, 40, new String[] { "stop_2.png", "stop_1.png", "stop_0.png" } );
  btnStop.addEventHandler(this, "btnStop_click");
  btnReloadThumbnail = new GButton(this, 580, 10, 120, 20);
  btnReloadThumbnail.setText("reload thumbnail");
  btnReloadThumbnail.addEventHandler(this, "btnReloadThumbnail_click");
  btnSelectFolder = new GButton(this, 110, 40, 53, 23);
  btnSelectFolder.setText("select");
  btnSelectFolder.addEventHandler(this, "btnSelectFolder_click1");
  label1 = new GLabel(this, 10, 40, 100, 20);
  label1.setText("Target folder");
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel lblFileUpload; 
GLabel lblProgress; 
GSlider sldrProgress; 
GDropList dlFolder; 
GLabel lblFolder; 
GLabel lblSubfolder; 
GDropList dlSubfolder; 
GButton btnSelectScan; 
GTextArea txtLog; 
GButton btnUpload; 
GTextField txfdScan; 
GTextField txfdFolder; 
GLabel lblProcessLog; 
GImageButton btnStop; 
GButton btnReloadThumbnail; 
GButton btnSelectFolder; 
GLabel label1; 
